name: Environment and Contexts
on: [push]

env:
  WF_LEVEL_ENV: Available to all jobs

jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
    env:
      JOB_LEVEL_ENV: Available to all steps for this job
    steps:
      - name: Logs ENV VAR
        run: echo $JOB_LEVEL_ENV
      - name: Logs context
        run: echo '${{ github.ref }}'
      - name: Logs custome env vars
        env:
          STEP_LEVEL_ENV: Available to this step only
          WF_LEVEL_ENV: Overriding the WF_LEVEL_ENV
        run: |
          echo ${{ env.WF_LEVEL_ENV }}
          echo $STEP_LEVEL_ENV
          echo $WF_LEVEL_ENV
          echo $JOB_LEVEL_ENV