name: Expressions and Contexts
on:
  pull_request:
    types: [ labeled ]
run-name: "Expressions and Contexts triggered by @${{ github.actor }} with event is ${{github.event_name }}"

jobs:
  runs-on-issues-and-prs:
    runs-on: ubuntu-latest
    if: contains(fromJson('["issues","pull_request"]'), github.event_name)
    steps:
      - name: Run only if issue has a bug label
        if: ${{ github.event.label.name == 'bug' }}
        run: echo 'This is an issue with a bug label'
        
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'