name: Expressions and Contexts
on: [ push, pull_request, issues, workflow_dispatch ]
run-name: "Expressions and Contexts triggered by @${{ github.actor }} with event is ${{github.event_name }}"

jobs:
  using_expressions_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        if: github.event_name == 'push'
        run: |
          echo ${{1}}
          echo ${{'This is a string'}}
          echo ${{null}}
          echo ${{true}}
          echo ${{1>2}}
          echo ${{'string' == 'String'}}
          echo ${{true && false}}
          echo ${{true || (false && true)}}
      - name: Dump Context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(secrets) }}'