name: Workflow run
on:
  workflow_run:
    workflows:
        - "Repository Events"
    types: [completed]

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i was triggered because 'Repository Events' workflow was completed"